# Site

title: Sepe Test
email: your-email@example.com
description: Studio creativo & sviluppo web.
baseurl: ""
url: ""

# Build

theme: minima
plugins:
  - jekyll/vite
  - jekyll-feed

# Paths

source: .
destination: _site
include:
  - docs
exclude:
  - bin
  - config
  - vite.config.ts
  - tmp
  - Procfile.dev
  - node_modules
  - vendor

# Defaults

defaults:
  - scope:
      path: "docs"
      type: pages
    values:
      layout: page
